### ISSUE TITLE
Cached assets seems to take longer to load than when reading from file

### ISSUE THREAD

**Issue by danfragoso** [jamesmartin/inline_svg#108]
I have around 1.000 svg icons. And testing a partial with 33 icons, but the problem is when I enable the cache the load time increase by almost 10 times.

This is the time to render the partial without the cache code
![2019-12-13-163327_301x207_scrot](https://user-images.githubusercontent.com/6226538/70827288-ad374780-1dc7-11ea-9ebb-94fa6dce0dbb.png)

This is the time to render the partial with the cache code
![2019-12-13-162852_328x305_scrot](https://user-images.githubusercontent.com/6226538/70827604-5f6f0f00-1dc8-11ea-8323-3cf89d80a297.png)

This is the code that I use to enable cache
```
#config/initializers/inline_svg.rb
InlineSvg.configure do |config|
  config.asset_file = InlineSvg::CachedAssetFile.new(
    paths: [Rails.root.join('app', 'assets', 'icons')],
    filters: /\.svg/
  )
end
```

**Comment by jamesmartin** [comment]
Thanks for opening this issue. ✨ 

Do you have a barebones example rails app that demonstrates this behavior? Does this happen with only a single SVG in the cache? Or does the load time increase in relation to the number of cached assets?

**Comment by danfragoso** [comment]
Yes, here is the link:
[](https://github.com/GabrielErbetta/miniature-succotash)
When there's only one icon it seems to work, but it's really slow with all the icons...

**Comment by danfragoso** [comment]
Bump

**Comment by jamesmartin** [comment]
@danfragoso sorry I haven't had a chance to update this issue. I'll make some time to look into this in the next week.

**Comment by stevendaniels** [comment]
I bumped into this issue recently. While I don't have time to work on a solution, my coworker and I did notice that the key lookup the `CachedAssetFile` could be optimized.

https://github.com/jamesmartin/inline_svg/blob/v1.3.1/lib/inline_svg/cached_asset_file.rb#L23-L53

Following a similar approach, something like this might help:

```ruby
def initialize(paths: [], filters: [])
   #...
   @sorted_asset_keys = assets.keys.sort { |a, b| a.string.size <=> b.string.size }
end

def key_for_asset(asset_name)
  @sorted_asset_keys.find { |k| k.ends_with?(string) } #or using regex
end
```

Alternatively, using `select` and `match?` instead of `map` and `match` might speed things up enough.
