### ISSUE TITLE
Add support for viewBox svg field

### ISSUE THREAD

**Issue by djsegal** [jamesmartin/inline_svg#119]
That and `fill` are two of the svg fields that are currently not supported. Is there a reason for this?

**Comment by jamesmartin** [comment]
@djsegal thanks for opening this issue. I'm not sure exactly what you're asking for… What would you like this gem to do that it doesn't already? (Examples are appreciated)

**Comment by euxx** [comment]
Hi @jamesmartin, I think @djsegal suggested adding two more options to `inline_svg_tag` to support svg attributes:  `fill` and `viewBox`

Example:
```rb
inline_svg_tag 'example.svg', fill: 'currentColor', view_box: '0 0 100 100'
```
would be
```html
<svg fill="currentColor" viewBox="0 0 100 100">
  ...
</svg>
```

**Comment by jamesmartin** [comment]
Thanks for clarifying, @euxx. ✨ 

I'll keep this open to track interest in this feature. For now, it should be possible for people that want this behavior to implement it themselves using a [custom transformation](https://github.com/jamesmartin/inline_svg/tree/0c2a01645b1ff71eab704012c6030d7fd7e220c5#custom-transformations).

**Comment by euxx** [comment]
Yeah, `custom transformation` should be enough for now.

Thanks for this convenient gem~
