### ISSUE TITLE
Request: 1.7.2 release

### ISSUE THREAD

**Issue by davefp** [jamesmartin/inline_svg#122]
Hi! Apologies if this is the wrong place to ask.

We're using the gem in an app with >1000 SVGs, and could really make use of the caching improvements introduced by #118.

We're pinning to the appropriate commit SHA for now but a proper taged release would be beneficial for us and others in our position. I can open a PR if it would be welcomed.

**Comment by jamesmartin** [comment]
👋 hello @davefp. Thanks for reminding me to make a new release. Apologies it's taken so long. The change you want is now in [v1.7.2](https://github.com/jamesmartin/inline_svg/releases/tag/v1.7.2).
