### ISSUE TITLE
Webpacker 6 support

### ISSUE THREAD

**Issue by AlecRust** [jamesmartin/inline_svg#130]
I tried upgrading from Webpacker 5.x to 6.x and `inline_svg_pack_tag` no longer works.

Are you considering Webpacker 6 support?

In the meantime I'm considering switch to a [hand rolled solution](https://blog.adrianthedev.com/rails-webpacker-inlinesvg-performance-issue) that looks to have better performance and will likely continue to work with Webpacker 6.

**Comment by jamesmartin** [comment]
Thanks for opening this issue. 

> Are you considering Webpacker 6 support?

I'm not against the idea but I also don't use Webpacker in any projects currently and don't have a huge amount of time to dedicate to this right now. 

Other people from the community have been contributing Webpacker support up to now, so I've added the "help wanted" label and hopefully somebody with the time and inclination will come along to help us out! 🤞

**Comment by fa11enangel** [comment]
Webpacker was retired and webpacker 6 will never arrive, so this ticket can be closed.

see also: https://mobile.twitter.com/rails/status/1483772667756957699

**Comment by jamesmartin** [comment]
Thanks for the update, @fa11enangel. 👍
