### ISSUE TITLE
Bump version rubygems

### ISSUE THREAD

**Issue by navidemad** [jamesmartin/inline_svg#135]
Hello,

Thanks again for your awesome gem.

Could you push the new version as there is interesting commit pushed to main branch

Otherwise we have to reference the github main in our Gem.

Have great day

**Comment by jamesmartin** [comment]
👋 thanks for the reminder, @navidemad. ✨ 

[Version 1.8.0](https://github.com/jamesmartin/inline_svg/releases/tag/v1.8.0) is now available.
