### ISSUE TITLE
NoMethodError with rails 7/propshaft

### ISSUE THREAD

**Issue by nickcoyne** [jamesmartin/inline_svg#145]
I'm getting this error when trying to use inline_svg with Rails 7 and propshaft:

```
NoMethodError:
  undefined method `assets_manifest' for #<XXX::Application>
     
          manifest = ::Rails.application.assets_manifest
```

**Comment by jamesmartin** [comment]
Thanks for letting me know. If you have a simple demo app that reproduces this bug that would also be very helpful.

**Comment by nickcoyne** [comment]
It seems I overlooked a config setting `config.asset_finder = InlineSvg::PropshaftAssetFinder` which resolves the issue.
