### ISSUE TITLE
Why in documentation it is mentioned that support for Rails 7 is experimental? 

### ISSUE THREAD

**Issue by bunufi** [jamesmartin/inline_svg#147]
![image](https://user-images.githubusercontent.com/12247686/225608531-15c2558c-5f83-4a7b-9558-e0b89a9d1979.png)

**Comment by jamesmartin** [comment]
I think the readme probably needs to be updated. The gem is definitely working in production with Rails 7.

**Comment by jamesmartin** [comment]
I've updated the readme to confirm that Rails 7 is supported. Thanks for raising this issue. ✨
