### ISSUE TITLE
`inline_svg_tag` Adds extra space after output

### ISSUE THREAD

**Issue by fredboyle** [jamesmartin/inline_svg#149]
In the following example code:
```erb
<a href="https://nowhere.invalid"><%= inline_svg_tag "interface/interface_smile.svg" %>No gear</a>
```
A whitespace character is added to the "No gear" string.

The output ends up being:
```html
<a href="..."><svg>...</svg> No gear</a>
```

Expected output:
```html
<a href="..."><svg>...</svg>No gear</a>
```

Investigating the issue a fix was found when modifying `lib/inline_svg/transform_pipeline.rb` in the "inline_svg" gem by changing line #7 to:
```ruby
end.to_html.strip!
```

Could this fix be implemented or is there an alternative solution to remove the extra space that shouldn't be there?

**Comment by jamesmartin** [comment]
Thanks for opening this issue and suggesting a fix. ✨ 

Please feel free to open a Pull Request with your suggested change and I'll get it merged into the Gem. Bonus points for writing a test that reproduces the problem. 👍

**Comment by fa11enangel** [comment]
@fredboyle please close the issue as it was merged/fixed.
