### ISSUE TITLE
Specs not running on main

### ISSUE THREAD

**Issue by trobrock** [jamesmartin/inline_svg#153]
@jamesmartin I'm working on putting a PR together to clean up all the rubocop work + #151 

The specs don't seem to run on main right now and before I continued down the debugging path I wanted to know if I was doing something wrong.

You can see the failed run on this empty commit actions of my fork: https://github.com/trobrock/inline_svg/commit/5679554394299fcf7f08f27a78e78bba3fc37b67

**Comment by xymbol** [comment]
> The specs don't seem to run on main right now and before I continued down the debugging path I wanted to know if I was doing something wrong.

I submitted #152 two weeks ago to fix the specs. Please check if that works for you.

**Comment by trobrock** [comment]
@xymbol thanks, that fixed it!
