### ISSUE TITLE
Support Shakapacker 8

### ISSUE THREAD

**Issue by tagliala** [jamesmartin/inline_svg#156]
Shakapacker 8 removed `Webpacker` spelling ref: shakacode/shakapacker#429

This is preventing CI to pass: https://github.com/diowa/icare/pull/1725

I'm working on a PR

**Comment by tagliala** [comment]
@leondmello can you test this branch? https://github.com/tagliala/inline_svg/tree/feat/support-shakapacker

**Comment by jamesmartin** [comment]
Apologies for the lack of updates recently. I'll be moving forward with support for Shakapacker 8, roughly following [the strategy outlined by @tagliala](https://github.com/jamesmartin/inline_svg/pull/158#issuecomment-2241158893).

In addition, I'll be bumping this gem to 2.0, at which point it will drop official support for the older versions of Rails and will move to align with the [official Rails maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html), which means versions of Rails that have reached end-of-life will not be supported.

**Comment by leondmello** [comment]
> @leondmello can you test this branch? https://github.com/tagliala/inline_svg/tree/feat/support-shakapacker

Thanks for the fix!
Sorry, couldn't check this earlier.
