### ISSUE TITLE
Drop webpacker support in favour of Shakapacker

### ISSUE THREAD

**Issue by tagliala** [jamesmartin/inline_svg#162]
Webpacker was deprecated and replaced with shakapacker.

CI is currently based on webpacker 4, which requires python 2.7, which is not available anymore. So it should be upgraded to webpacker 5, which is in EOL

Because of #161 and a major release, I would also drop webpacker

**Comment by jamesmartin** [comment]
We'll be completely dropping support for EOL versions of Rails in a version 2.0 of this gem, which I expect to have released very soon. 🤞

**Comment by jamesmartin** [comment]
Interim [version 1.10.0](https://github.com/jamesmartin/inline_svg/releases/tag/v1.10.0) has been released, which includes your support for Shakapacker v8. I'll get working on v2.0 of this gem in the coming weeks, in which we'll drop support for Webpacker.
