### ISSUE TITLE
Embedding SVG image stored on AWS 

### ISSUE THREAD

**Issue by l3iodeez** [jamesmartin/inline_svg#17]
I am trying to use this tool to embed a SVG image that is stored on an AWS S3 cloud storage server. 
I am able to properly embed the image if its stored on my Rails server but if I pass the AWS url of my SVG to your gem as shown below the image does not display and I get the error message:
     <code></code>

in the generated source. 

If I paste that URL into my browser I am able to see the image. 

Is there any way to use your tool to embed an SVG that is stored on S3?

Thanks!

**Comment by jamesmartin** [comment]
Hi @l3iodeez, unfortunately `inline_svg` only currently works with local assets accessible via `Sprockets`. 

I can't think of a quick way to implement this feature currently, so I'll need to give it some thought. Do you have any suggestions for how this could work *and* perform well (I would guess we should cache remote files and transforms somehow)? I've been considering a client-side counterpart library that could do remote transforms and embeds.

**Comment by l3iodeez** [comment]
I agree that the SVGs would need to be locally cached for performance reasons. The rationale for doing this is so that my users can upload the images through a form instead of having include them in the repo, since Im using Heroku and it doesn't allow the saving of files directly to the server.

**Comment by jamesmartin** [comment]
I don't think caching on the server side would work very well in this case (user uploads or dynamic content), especially given the restrictions on file system access with Heroku. 

The more I think about it, the more a client-side solution seems correct. Does your application have any restriction on Javascript compatibility or hard requirement for HTML fallback?

For the case where JavaScript is unacceptable, perhaps we could consider storing the transformed SVGs in a database.

**Comment by l3iodeez** [comment]
Javascript is required for my app, so caching the SVGs client side would work, though I have to admit I don't really know how you would implement this.

**Comment by jamesmartin** [comment]
There are three possible solutions I'm weighing:

1. Duplicate much of the server-side transformation logic into some companion Javascript code, which would be responsible for getting the remote SVG from the client's browser and doing the specified transformation client-side. The results could be cached using local storage, or similar.
1. Expose a rails server endpoint (perhaps via an engine), which would do the transformations and caching on behalf of the client-side Javascript. In this scenario, the Javascript would still be responsible for fetching the SVG from the remote URL, but could then pass the SVG to the rails server for transformation.
1. Keep all fetching and transforming on the server-side, but perform the work out-of-band of the page request/response cycle (some kind of queuing), then allow the client-side to poll the server for the file and receive it once the fetching/transforming is done.

There are benefits and drawbacks to each approach, so I want to think it through carefully before committing to one direction.

**Comment by l3iodeez** [comment]
It seems like the first option would be the simplest to implement, but I have to admit I don't really know how the other two would work.

**Comment by jamesmartin** [comment]
Agreed. I'm going to start on option 1 this week. Not sure if it's going to be a separate library or bundled as part of this gem. 

The changes to this gem would involve detecting the presence of a URI scheme in place of a filename and then inserting the transformations into a DOM element (probably as data attributes) for the JavaScript to use for the transformations.

**Comment by jamesmartin** [comment]
@l3iodeez I just found a JavaScript library called [inline-svg](https://github.com/jonnyhaynes/inline-svg), which seems to be almost exactly what we want.

I'm thinking of modifying the Rails helper to simply insert an `<img>` tag suitable for the `inlineSvg` JavaScript library to consume and convert.

The only thing that might be a problem for you is that `inlineSvg` removes `xmlns:xlink` directives from SVG documents. We could always submit a pull request to this library to prevent this happening.

**Comment by l3iodeez** [comment]
I took a look at that JS library and it does seem like it would do the trick, and it would be a simple matter to take out the line that removes the xlink. Ill fork the library and give it a try.

**Comment by l3iodeez** [comment]
Hm. I'm able to get that JS library working with locally stored SVGs (with working link) but if I point to the AWS url instead of just the filename then it leaves the <img> tag unaltered, any ideas?

**Comment by jamesmartin** [comment]
I haven't had a chance to try it myself. I'm going to be a away for a week, so I probably won't have a chance to look at this until June 15. 

I'm probably going to write another JavaScript library to work alongside `inline_svg`, so maybe this won't be a big problem.

**Comment by l3iodeez** [comment]
I was able to arrive at an acceptable solution using the inline-SVG.js library. My earlier problem was that I needed to enable CORS access in AWS.

**Comment by jamesmartin** [comment]
@l3iodeez, glad you figured it out.

I'm working on a [JavaScript library](https://github.com/jamesmartin/remote-svg) to play nicely with `inline_svg`. It's not ready yet, but I will update this issue when it's done.

**Comment by jamesmartin** [comment]
I finally released my own [Remote SVG Javascript library](https://github.com/jamesmartin/remote-svg). It's based entirely on ES6 (with SystemJS and jspm) and has no dependency on jQuery. This probably makes it *less* suitable for most Rails applications, but I think it's a  better solution for the long-term. The functionality is not quite the same as `inline_svg` — fewer transformations etc — but I'm working towards feature parity.
