### ISSUE TITLE
Links within SVG not working on Production

### ISSUE THREAD

**Issue by l3iodeez** [jamesmartin/inline_svg#18]
Inline_svg works great on my development server but on my Heroku production server the image displays but links within the SVG are not clickable. They links work properly in my dev environment. The section of the SVG that defines the link is included below. It seems to be rendering properly when I inspect it in the browser I just can'f see why the link is not clickable in production. 

Thanks a lot for this useful tool!

      <a
         xlink:href="/ahera/4/0018"
         target="_self"
         id="a3719">
    <g
       transform="matrix(1.5590249,0,0,1.6419366,-227.98065,-17.031852)"
       id="MTEXT">
   
        <text
           style="font-size:7px;font-family:ArialMT;fill:#000000;stroke:#000000;stroke-width:0.25;stroke-miterlimit:10"
           transform="translate(390.1582,126.8423)"
           stroke-miterlimit="10"
           font-size="7"
           id="text3721">0018 -</text>
        <text
           style="font-size:7px;font-family:ArialMT;fill:#000000;stroke:#000000;stroke-width:0.25;stroke-miterlimit:10"
           transform="translate(390.0996,135.0229)"
           stroke-miterlimit="10"
           font-size="7"
           id="text3723">Classroom</text>
        <text
           style="font-size:7px;font-family:ArialMT;fill:#000000;stroke:#000000;stroke-width:0.25;stroke-miterlimit:10"
           transform="translate(389.7012,143.144)"
           stroke-miterlimit="10"
           font-size="7"
           id="text3725">18</text>
     
    </g>
     </a>.

**Comment by jamesmartin** [comment]
Do you see any difference in the embedded documents rendered on your local development environment and your production environment?

Can you replicate the problem locally by running a rails server in production mode?

**Comment by l3iodeez** [comment]
Thanks for your advice, I realize this is very likely to not actually have anything to do with inline_svg, so I appreciate your helping me to troubleshoot.  

I  ran a comparison on the source code and it seems certain terms  (most importantly the xlink: term in my embedded link) are being dropped from the SVG when it renders on my heroku production server. This does not happen when running in local production mode. 

The link looks liek this on production:
<a href="/ahera/4/0018" target="_self" id="a3719">

and like this in development:
<a xlink:href="/ahera/4/0018" target="_self" id="a3719">

If I edit the HTML in place using my browser debug tool then the link works. Any idea why this might be happening?

**Comment by l3iodeez** [comment]
If I paste the SVG code directly in my html rather than using inline_svg to call it then the link works so it does appear this has something to do with inline_svg. 

Thanks again for your help.

**Comment by jamesmartin** [comment]
Thanks for the further information. I wonder if you could provide:

1. An example input SVG that exhibits the behavior
2. The exact options you pass to the inline_svg function inside your view template

I'll try to reproduce locally. I wonder if this has something to do with the cleaning we do with Loofah (nocomment option).

**Comment by l3iodeez** [comment]
I created a single element SVG but when I tested it on heroku its links and those in the other SVG file are now working. Im not sure what I did that caused it to start working, but when I do I will post back in case anyone else runs into this problem. 
Thanks again!

**Comment by jamesmartin** [comment]
Glad it worked itself out. Would be very interested to hear about the cause if you ever find out.

**Comment by l3iodeez** [comment]
I was able to determine that the SVG tag must include the line: "xmlns:xlink="http://www.w3.org/1999/xlink"

I had removed what I thought was extraneous info from the SVG header, but if that line is not included part of the <svg> tag or "xlink" will get dropped from the href and the links won't work. This only occurs on my heroku production server.

**Comment by jamesmartin** [comment]
@l3iodeez that's really interesting. The [w3 spec](http://www.w3.org/TR/xlink/#att-method) does include documentation for this requirement, but it's very easy to miss:

> As dictated by [XML Names], the use of XLink elements and attributes requires declaration of the XLink namespace. For example, the following declaration would make the prefix xlink available within the myElement element to represent the XLink namespace:

```xml
<myElement
  xmlns:xlink="http://www.w3.org/1999/xlink">
  ...
</myElement>
```

I don't fully understand why it seemed to be working on your local development machine, but not on Heroku.
