### ISSUE TITLE
Precompilation requires "config.assets.compile = true" in production for sprockets-rails 3.0.0.beta2

### ISSUE THREAD

**Issue by dylanfareed** [jamesmartin/inline_svg#25]
This sprockets-rails PR removes `Rails.application.assets` in default rails production configs.
https://github.com/rails/sprockets-rails/pull/220

So in production precompilation, we ended up failing here:
https://github.com/jamesmartin/inline_svg/blob/18e6b1db0752a7989227dee475a1960699bdb45c/lib/inline_svg/railtie.rb#L15

```
 ✗ RAILS_ENV=production rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
rake aborted!
InlineSvg::Configuration::Invalid: Asset Finder should implement the #find_asset method
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/inline_svg-0.6.1/lib/inline_svg.rb:25:in `asset_finder='
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:15:in `block (2 levels) in <class:Railtie>'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/inline_svg-0.6.1/lib/inline_svg.rb:55:in `configure'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:12:in `block in <class:Railtie>'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `call'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/dylan/Desktop/smithson-web-dashboard/config/environment.rb:5:in `<top (required)>'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/dylan/.rvm/gems/ruby-2.2.3/gems/sprockets-rails-3.0.0.beta2/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/dylan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/dylan/.rvm/rubies/ruby-2.2.3/bin/rake:37:in `<main>'
Tasks: TOP => environment
```

Precompilation succeeds if we downgrade to sprockets-rails 3.0.0.beta1.

Precompilation also succeeds if we change the rails config in `config/environments/production.rb` from

```ruby
  config.assets.compile = false
```

to

```ruby
  config.assets.compile = true
```

That seems like too broad a brush for a fix here.

**Comment by jamesmartin** [comment]
@dylanfareed seems like I made a [bad assumption here](https://github.com/jamesmartin/inline_svg/blob/master/lib/inline_svg/railtie.rb#L15) (that `app.assets` would always be a working Sprockets instance).

 If I'm reading that change correctly, it looks like we might be able to fall back to the [`Sprockets::Rails::Helper#resolve_asset_path`](https://github.com/rails/sprockets-rails/blob/93a45b1c463a063ec7cf4d160107b67aa3db7a1a/lib/sprockets/rails/helper.rb#L74) method when `config.assets.compile = false`.

The asset finder in `InlineSvg` is also configurable, you just need to pass it an object that responds to `find_asset` and returns a file-like object that responds to `pathname`:

For example, to implement a really naive asset finder that only looks for assets in the `./public/images/` directory, you could do this in an initializer:

```ruby
class NaiveAssetFinder
  def self.find_asset(filename)
    new(filename)
  end

  attr_accessor :pathname

  def initialize(filename)
    @pathname = "#{Rails.root.join('public', 'images', filename)}"
  end
end

InlineSvg.configure do |config|
  config.asset_finder = NaiveAssetFinder
end
```

In the next few days I'll try to make the default a little more resilient to this Sprockets change.

**Comment by jamesmartin** [comment]
Experimented with Sprockets v3.0.0.beta2 today. When `config.assets.compile = false` there is very little chance of getting a properly configured `Sprockets` instance. Assets are now being served as static files from the `public/assets/` directory and they could even be on a CDN or other remote host. There is no guarantee that we can get access to them.

Changing the default `config.after_initialize` in the railtie to `config.asset_finder = app.config.assets` prevents things from exploding, but we also won't be able to resolve asset paths when `config.assets.compile = false`.

To accommodate this scenario we might be able to provide a configurable asset finder to replace Sprockets, which behaves a little like [my previous example](https://github.com/jamesmartin/inline_svg/issues/25#issuecomment-148220993), except it uses the built-in Rails `asset_path` helpers to obtain the correct pathname. People choosing this option could configure the library like so:

```ruby
InlineSvg.configure do |config|
  config.asset_finder = InlineSvg::StaticAssetFinder
end
```

**Comment by ryanswood** [comment]
FYI, Sprockets-rails 3.0 has been released for 5 days now so anyone who upgrades will be unable to compile in production.

**Comment by jamesmartin** [comment]
@ryanswood sorry about this, it hasn't been top priority over the holiday season. I'll take a look at it this week.

**Comment by ryanswood** [comment]
@jamesmartin Thank you. I ended up forking this repo and making basic changes to get it working again. This is my first time digging into Sprockets. My app is very basic at this point so I am serving assets from the app. Here is the change that I made: https://github.com/AbleHealth/inline_svg/commit/661bbb3bef7d1b4bd6ccd63f5f018305797b9509

**Comment by jamesmartin** [comment]
@ryanswood your change makes a lot of sense in this context. I'd be happy to include your StaticAssetFinder as the fallback instead of raising an exception in this case. Do you mind if I use your code?

**Comment by ryanswood** [comment]
@jamesmartin Go for it!

**Comment by jamesmartin** [comment]
Fixed in release [0.6.2](https://github.com/jamesmartin/inline_svg/releases/tag/v0.6.2).

I've implemented the [`StaticAssetFinder`](https://github.com/jamesmartin/inline_svg/blob/21c2883fe40be326d97a960071b06925e57f98e1/lib/inline_svg/static_asset_finder.rb) (thanks, @ryanswood), which we use as a fall-back for Sprockets 3.

There's a [test rails app](https://github.com/jamesmartin/inline_svg_test_app/tree/sprockets3) using this version with the new version of Sprockets and `assets.precompile = false` if you're interested in seeing it working.

Sorry this took so long. Thanks for your patience, @dylanfareed and @ryanswood.

**Comment by dylanfareed** [comment]
Thanks a ton for the follow up here @jamesmartin and @ryanswood. Greatly appreciate your work and time spent on this!

**Comment by meowsus** [comment]
Hey @jamesmartin 

We just hit this issue. Would it make sense to call out to this feature in the README?

Our issue was SVGs wouldn't appear in non-development environments. So while developing everything looked great, but once it's up on a staging/qa/production environment the SVG images were not found and, when those SVGs aren't found, we had some broken layouts here and there.

Truthfully it was a weird use case. We were using `inline_svg` within a `.jst.ejs.ruby` chain. Still a good head scratcher tho.
