### ISSUE TITLE
Changing the color requires to target the "path" children apparently

### ISSUE THREAD

**Issue by thbar** [jamesmartin/inline_svg#26]
Thanks for your work on inline_svg!

I tried using this from the readme:

```
.some-class {
  display: block;
  margin: 0 auto;
  fill: #3498db;
  width: 5em;
  height: 5em;
}
```

But in my case what worked really is instead:

```
.some-class {
  width: x,
  height: y,
  path: {
    fill: #3498db;
  }
}
```

Note that I'm just discovering the gem, so I may have missed something obvious :smile: but this made this work for me. Thanks again!

**Comment by jamesmartin** [comment]
Interesting. What does your SVG document look like?

**Comment by 2metres** [comment]
@thbar Sounds like you need to add class names inside your svg markup, because the gem only applies the class name to the `<svg>` element

```svg
<svg class="[ inline_svg_class ]" >
   <path class="primary">…</path>
   <path class="secondary">…</path>
</svg>
```
then you can write css like this
```scss
[ inline_svg_class ] {
  .primary {
     fill: red;
  }
  .secondary {
    fill: green;
  }
}
```

**Comment by jamesmartin** [comment]
@thbar did this solve your problem? I'll reopen this issue if you need more help.

**Comment by thbar** [comment]
I cannot test it anymore - I do not have access to the code base at this
point !
Le dim. 1 mai 2016 à 03:37, James Martin <notifications@github.com> a
écrit :

**Comment by smellyshovel** [comment]
I have the same problem too.
Here is CVG:
```
<svg viewBox="0 0 24 24">
    <path fill="#000000" d="M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2C6.47,2 2,6.47 2,12C2,17.53 6.47,22 12,22C17.53,22 22,17.53 22,12C22,6.47 17.53,2 12,2M14.59,8L12,10.59L9.41,8L8,9.41L10.59,12L8,14.59L9.41,16L12,13.41L14.59,16L16,14.59L13.41,12L16,9.41L14.59,8Z" />
</svg>
```
Here is HTML (HAML):
`%span{class: "close"}= inline_svg("icons/flash-close.svg", class: "some-class")`

And if my CSS looks like this,
```
span.close {
    width: 2em;
    height: 2em;

    svg {
      @extend span.close;
      fill: #3498db;
    }
  }
```
the color doesn't change.
But if CSS looks like this,
```
span.close {
    width: 2em;
    height: 2em;

    svg > path {
      @extend span.close;
      fill: #3498db;
    }
  }
```
the color changes.
What can it be? Cause it's not very convinient to me to explicitly match 'path' tag all the time (for some reasons). Thanx!

**Comment by jamesmartin** [comment]
@smellyshovel I think the problem with your first SVG is that the `path` element explicitly sets a `fill` attribute, which sets the color of the element:

```
 <path fill="#000000" 
```

This means that your original CSS was lower precedent (less specific) than the existing `fill` attribute on the element and so the browser prioritized the `#000000` value. When you added the `svg > path` selector, your CSS rule was specific enough to override the `fill` attribute.

The reason your second SVG behaves the way you expect is because you no longer have the `fill` attribute on the `path` elements.

Does that make sense?

**Comment by smellyshovel** [comment]
You know, I think now that you are right, though it is not very logical. I think, that if you specify `fill:` for `path`, it should paint only that path. But if you specify `fill:` for full `svg`, it should paint FULL svg. And, you know? This concept works perfect in the second SVG, but doesn't work at all in the first one. Of course, it's not your fail. I just shared thoughts. Thank you for reply, I'll take note of this.

**Comment by jamesmartin** [comment]
> You know, I think now that you are right, though it is not very logical.

I agree. Web browser SVG support is slowly getting better, maybe one day it will be more logical.

**Comment by Blake-LeBlanc** [comment]
Thank you for your great gem @jamesmartin , I just discovered it and it's been really useful for getting svg elements into the views!

First time using svg files and I'm running into a similar issue. I see others have mentioned referencing the "path" if the fill is set there. That seems to be what's going on in my case, but I'm not sure what syntax to use.

Here's the source code for one of the svg elements, it's a simple hollowed out circle

```
<!-- Created with Inkscape (http://www.inkscape.org/) --><svg xmlns="http://www.w3.org/2000/svg" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:xlink="http://www.w3.org/1999/xlink" width="10" height="10" version="1.1" viewBox="0 0 4.0791 4.0794" class="active">
--
  | <metadata>
  | <rdf:RDF>
  | <cc:Work rdf:about="">
  | <dc:format>image/svg+xml</dc:format>
  | <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"></dc:type>
  | <dc:title></dc:title>
  | </cc:Work>
  | </rdf:RDF>
  | </metadata>
  | <g transform="translate(8.8444 -43.916)">
  | <path id="path10" d="m-2.1973 43.916a2.0396 2.0396 0 0 0-2.0395 2.0397 2.0396 2.0396 0 0 0 2.0395 2.0397 2.0396 2.0396 0 0 0 2.0396-2.0397 2.0396 2.0396 0 0 0-2.0396-2.0397zm0 0.66035a1.379 1.379 0 0 1 1.379 1.379 1.379 1.379 0 0 1-1.379 1.379 1.379 1.379 0 0 1-1.379-1.379 1.379 1.379 0 0 1 1.379-1.379z" fill="#666"></path>
  | <circle id="path15" cx="-2.1973" cy="45.956" r=".97658" fill="#666"></circle>
  | <path d="m-6.8049 43.916a2.0396 2.0396 0 0 0-2.0395 2.0397 2.0396 2.0396 0 0 0 2.0395 2.0397 2.0396 2.0396 0 0 0 2.0396-2.0397 2.0396 2.0396 0 0 0-2.0396-2.0397zm0 0.66035a1.379 1.379 0 0 1 1.379 1.379 1.379 1.379 0 0 1-1.379 1.379 1.379 1.379 0 0 1-1.379-1.379 1.379 1.379 0 0 1 1.379-1.379z" fill="#666"></path>
  | <g transform="matrix(.10058 0 0 .10058 15.929 31.985)" fill="#666">
  | <rect transform="rotate(-60)" x="-141.49" y="-42.341" width="6.949" height="13.898"></rect>
  | <rect transform="rotate(30)" x="-29.796" y="111.02" width="7.6172" height="30.469"></rect>
  | </g>
  | <g transform="matrix(.12264 0 0 .12264 -7.7598 34.378)" fill="#0a0">
  | <path d="m118.91 77.774a16.631 16.631 0 0 0-16.631 16.631 16.631 16.631 0 0 0 16.631 16.631 16.631 16.631 0 0 0 16.631-16.631 16.631 16.631 0 0 0-16.631-16.631zm0 5.3862a11.245 11.245 0 0 1 11.245 11.245 11.245 11.245 0 0 1-11.245 11.245 11.245 11.245 0 0 1-11.245-11.245 11.245 11.245 0 0 1 11.245-11.245z"></path>
  | <g transform="matrix(.82016 0 0 .82016 196.9 11.222)">
  | <rect transform="rotate(-60)" x="-141.49" y="-42.341" width="6.949" height="13.898"></rect>
  | <rect transform="rotate(30)" x="-29.796" y="111.02" width="7.6172" height="30.469"></rect>
  | </g>
  | </g>
  | <use transform="translate(4.5427)" width="100%" height="100%" opacity="0" xlink:href="#path10"></use>
  | <use transform="translate(4.3952 -.1475)" width="100%" height="100%" xlink:href="#path15"></use>
  | </g>
  | </svg>
```
On the css side, I'm using scss, trying to reference it this way:

          .dotbar-wrapper {
            position: absolute;
            bottom: 2px;
            width: 60%;
            cursor: pointer;

            .dot {
              svg > path {
                fill: $active-color;
              }
            }
          }

Any ideas where I'm going wrong? Thank you all in advance!

**Comment by Blake-LeBlanc** [comment]
@jamesmartin Nevermind, I just figured it out!

For scss syntax, it's referenced as

    svg path {
      fill: $active-color;
    }

Awesome, now it's off to the races :)

Thanks again for all the work you put into this!
