### ISSUE TITLE
Problems with multiple SVG inlined on same page due to embedded style tags

### ISSUE THREAD

**Issue by coneybeare** [jamesmartin/inline_svg#27]
I have come across a bug which is not entirely `inline_svg`s fault, but needs to be handled in the gem.

When you have two embedded svgs on the same page, the `style` tags that are contained in each svg can conflict... often because the same designer used the same layer names or styles in the original document. There are not namespaces per document inlined svg, and no natural separation as when letting the browser load from file,  so when embedding multiple files in the page, the style tag of the second svg tag will effect the first.

For example, here are two style tags which are both valid in their own documents, but make a problem when embedded on the same page

````
<style type="text/css">.st0{fill:#F6B62E;} .st1{display:none;fill:#181818;} .st2{fill:#181818;}</style>
<style type="text/css">.st0{fill:#181818;} .st1{fill:#F6B62E;}</style>
````

[Here](https://github.com/jamesmartin/inline_svg/files/94954/inline_svg_bug.zip) is a sample project showing the issue.

Possible solution approaches:

1. Rewrite the style tag when embedding to use the HTML5 [scoped attribute](http://www.w3.org/TR/html-markup/style.html#style.attrs.scoped): `style scoped='true'...`
2. Rewrite the style tag to prepend a class that has a unique id, one you also assign to the containing .svg: `.deadbeef. st0{...` 
3. Replace all classes and ids in the svgs with a string that prepends them with a certain unique val: : `.deadbeef_st0{...` and `path class=`.deadbeef_st0`

Unfortunately, 1 seems to be a dead end due to [lack of browser support](http://caniuse.com/#search=scoped). 3 seems safest, but requires more editing of the file, and more text insertion.

2 seems like a good balance, only adding a unique val in a few places: the svg's class tag, and the prepended in the individual styles within the style tag. The `path` and `g` elements would not need manipulation.

Thoughts?

**Comment by coneybeare** [comment]
For further reference, here is a shot of the 2 inlined svgs i used in the example project on the same page.

![screen shot 2016-01-18 at 3 46 26 pm](https://cloud.githubusercontent.com/assets/35369/12402396/ca39b664-bdfa-11e5-875c-b01c5f641a9c.jpg)


And here is what the top one should look like solo, a simple color reversal.

![screen shot 2016-01-18 at 3 46 39 pm](https://cloud.githubusercontent.com/assets/35369/12402400/d4df5c9a-bdfa-11e5-9982-c62756eb2200.jpg)

**Comment by jamesmartin** [comment]
@coneybeare, thanks for the detailed description of this issue and the proposed options :+1: 

I'm reluctant to add this behavior to the gem for a number of reasons:

* I'm keen to make the core functionality of the gem simple (handle fewer special cases)
* If we choose one of a possible three solutions, it's entirely likely that people will request support for the other two
* It's possible to extend the document transformation pipeline and achieve any one of your suggested solutions by writing a [custom transformation](https://github.com/jamesmartin/inline_svg#custom-transformations)

As a less automated workaround, one could completely remove the `<style>` tags from an SVG document and supply an external stylesheet to target and style each document's classes separately.

What do you think?

If you need help writing a custom transformation, let me know and I'll come up with an example to get you started.

**Comment by coneybeare** [comment]
I'll start with a transformation. I guess I just thought that the problem would be more widespread. Is it uncommon for there to be multiple svgs on the same page? Maybe I am just making my art wrong?

**Comment by coneybeare** [comment]
I started on this, but the nature of the style tag is that it can be anywhere in the svgs document, there can be numerous tags, each one is usually a cdata which would require difficult text parsing of styles... so yeah. I give up.

An easier solution is to regenerate my svgs using AI's `presentation attributes` selection instead of `style elements` when saving in AI.

[Here is some more info on those AI settings](http://articles.dappergentlemen.com/2014/12/17/demystifying-illustrator-svg-css/) 

![screen shot 2016-01-24 at 10 25 22 am](https://cloud.githubusercontent.com/assets/35369/12537092/f7ff5804-c284-11e5-8c5b-2a9a2379f577.jpg)

**Comment by jamesmartin** [comment]
> Is it uncommon for there to be multiple svgs on the same page?

I think the usage of SVGs on the web, especially in embedded form, is relatively limited (compared to images and pure CSS). 

This gem is, in part, a response to finding it difficult to use SVGs in the real world. The original use-case was to have many of the same SVG displayed on a page, and styled differently (colors, sizes etc.) with external CSS, hence the need to embed and then add classes to the root-level document. I usually lean towards stripping out as much presentation information as possible, and doing all coloring, sizing etc. in external CSS. This gives the maximum flexibility.

Of course, if you're producing SVG documents for standalone use, then I can understand the desire to have embedded style information.

Thanks again for trying to come up with a solution and for preserving your findings for others to refer to later. :sparkles:

**Comment by englishextra** [comment]
giv svg a unique id and use that in embedded into svg style tag
