### ISSUE TITLE
Can't find SVG

### ISSUE THREAD

**Issue by rctneil** [jamesmartin/inline_svg#29]
Hey,

I can't get your gem to find my SVG's. I am not using the Asset Pipeline but have a custom Gulp setup. I have a custom gulp_asset_path helper and am using it like this:

inline_svg(gulp_asset_path('svgs/caricature.svg'))

This gives the path as: /assets/svgs/caricature.svg but it still fails.

Any way for me to fix this?

Thankyou

**Comment by jamesmartin** [comment]
@rctneil if you've disabled the asset_pipeline (`config.assets.compile = false`), by default inline_svg will just look at your `Rails.root` manifest directory (`Rails.application.assets_manifest.directory`), and then append the asset path you pass (e.g. `/assets/svgs/caricature.svg` in this case).

Could you find out what your application's `assets_manifest.directory` is?

**Comment by feitla** [comment]
We have the same issue, using gulp build. Our `Rails.application.assets_manifest.director` is `/public/assets`. Our SVG lives in `/public/assets/images/svg/some.svg` and we are referencing this svg in the view as, `= inline_svg "images/svg/some.svg"` but are still getting `SVG file not found` error message. Please advise?

**Comment by paraboom** [comment]
I have the same situation. We have `webpack-dev-server` in development environment and all my assets are on `localhost:4000`, so gem can't find svgs if I pass absolute path like: `//localhost:4000/assets/roadtrip/headline_mobile.svg`. Can you add support of remote paths?

**Comment by jamesmartin** [comment]
@feitla sorry for the delay in responding (vacation). 

I'm not super familiar with how gulp and rails play together, but I'd start by checking the path that the `gulp_asset_path` helper is returning when you pass it your SVG as an argument:

`%h1=gulp_asset_path("images/svg/some.svg")`

The code we use for finding assets is pretty naive without the asset pipeline, so I could imagine it being a mismatch between what we expect and what `gulp_asset_path` resolves to.

**Comment by jamesmartin** [comment]
> Can you add support of remote paths?

@paraboom I've considered adding support for remote paths, but actually decided it wasn't a good fit for this gem. There's a pretty big discussion in issue #17. 

I eventually went down the path of writing a separate JavaScript module ([remoteSvg](https://github.com/jamesmartin/remote-svg)) to do remote SVG embedding. It's not finished to the same level as this gem, but it's probably more suitable.

That said, if you have any ideas about how we could sensibly build remote path support into this gem, I'd love to hear them. Maybe open a separate issue, so we can discuss there.

**Comment by jamesmartin** [comment]
If anybody figures out what's happening with their gulp paths I'll reopen this.
