### ISSUE TITLE
Feature Request: Strip Global Styles

### ISSUE THREAD

**Issue by Undistraction** [jamesmartin/inline_svg#40]
Illustrator bakes inline styles into the .svgs it exports which can cause lots of issues as it uses generic (identical) classnames for all its exports, so it's easy to end up with a race-condition between all svgs.

It would be great to be able to strip any inline styles from the embed.

**Comment by jamesmartin** [comment]
@Undistraction could this be done with a [custom transformation](https://github.com/jamesmartin/inline_svg#custom-transformations)? 

I'm reluctant to build more specific transformations into the library because it increases the maintenance overhead: For example, when illustrator changes the way it creates its XML markup output, `inline_svg` would have to follow suit and support both old and new versions.

**Comment by Undistraction** [comment]
I've renamed this isse as the styles aren't inline, but dumped at the top of the svg:

```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2 82">
  <defs>
    <style>
      .cls-1 {
        fill: #343434;
      }
    </style>
  </defs>
  <title>dotted_line</title>
  <path class="cls-1" d="M0,81a1,… 1ba" />
</svg>
```

I don't think it would need to do anything Illustrator-specific - just remove styles added within the `<defs>` tag.

**Comment by jamesmartin** [comment]
@Undistraction here's a custom transformation that will strip the style tag from your document:

```ruby
class StripIllustratorStyles < InlineSvg::CustomTransformation
  def transform(doc)
    doc = Nokogiri::XML::Document.parse(doc.to_html)
    doc.at_css('svg defs style').remove
    doc
  end
end
```

You can load it in an initializer like so:

```ruby
# config/initializers/inline_svg.rb
InlineSvg.configure do |config|
  config.add_custom_transformation(attribute: :strip_styles, transform: StripIllustratorStyles)
end
```

And use it like this:

```erb
<%= inline_svg('test.svg', strip_styles: true) %>
```

You can see all of that in action in this [test app](https://github.com/jamesmartin/inline_svg_test_app/commit/b68c589aca63d97bf66686e111cdf7311990bb76).

**Comment by Undistraction** [comment]
This is perfect. Thanks very much.
