### ISSUE TITLE
Can't find assets in production if '.svg' is forgotten

### ISSUE THREAD

**Issue by hansottowirtz** [jamesmartin/inline_svg#41]
So `inline_svg 'logo'` works in development, but not in production. `inline_svg 'logo.svg'` works in both. I think `InlineSvg::AssetFile` should append `.svg` if it is not present, or raise an Error.
```ruby
filename = "#{filename}.svg" unless filename.end_with?('.svg')
```
It is very confusing if this problem occurs.

**Comment by jamesmartin** [comment]
`inline_svg` always tries to use Sprockets to dynamically find files. The Sprockets asset finder is pretty lenient, allowing you to leave off the file extension. If you disable Sprockets in production and instead opt to serve precompiled assets (as many people do, for performance reasons), then we fall back to a naive asset finder, which simply looks in the `#{Rails.root.join("public")}` directory for the exact filename.

We could update the naive asset finder to append `.svg` if it's not present. The reason we don't raise an error when a file is not found is to mirror Rails' built-in image tag helpers, which will simply render the `<img ... />` tag regardless if the file exists. You should see a HTML comment in your rendered page that tells you the SVG file could not be found.

**Comment by hansottowirtz** [comment]
Didn't know that, very interesting! I think it's indeed a good idea to mirror the image_tag helpers. Maybe we could try clarifying the error message:

```ruby
if filename.ends_with? '.svg'
  "<svg><!-- SVG file not found: '#{filename}' --></svg>"
else
  "<svg><!-- SVG file not found: '#{filename}' (Try adding '.svg' to your filename) --></svg>"
end
```

**Comment by jamesmartin** [comment]
> Maybe we could try clarifying the error message

Good idea. We could add that hint if we're using the naive asset finder and not Sprockets.

**Comment by jamesmartin** [comment]
Fixed in [v0.9.1](https://github.com/jamesmartin/inline_svg/releases/tag/v0.9.1).

**Comment by madeindjs** [comment]
I discovered this issue in production environment. Why not simply put `.svg` extension when not present?

**Comment by jamesmartin** [comment]
> Why not simply put `.svg` extension when not present?

@madeindjs the reason I chose to add the empty `<svg>` tag is to match the behavior of Rails' built in helpers like `image_tag`, which don't care if the file specified exists, it just renders the `<img>` tag. I felt this would be more consistent and approachable to Rails developers. We added the extension "hint" as a convenience.
