### ISSUE TITLE
Feature Request: Better handling of existing class on SVG element

### ISSUE THREAD

**Issue by Undistraction** [jamesmartin/inline_svg#44]
It appears that if a class or classes already exist(s) on the svg element and 'inline-svg` is called using the `class` parameter, these classes are replaced. It would make more sense to me that any additional classes are added. If classes need to be scrubbed from the SVG then it feels like that should happen in a transform, not as an unexpected bi-product of adding a class. 

Additionally I need to add a class to all SVG elements. Obviously I could pass the same class every time I use `inline-svg`, but this feels like unnecessary repetition. I solved this by writing a transform that pulls a default class from config, but this would be a nice built-in config option.

**Comment by jamesmartin** [comment]
> It would make more sense to me that any additional classes are added.

@Undistraction agreed. This feels like the correct behavior.

> Obviously I could pass the same class every time I use inline-svg, but this feels like unnecessary repetition.

This would mean exposing the built-in transformations to the `configure` block, and allowing default values to be added. I'll have to think through the ramifications of this, as there's the potential for confusion here ("Where is this extra class coming from" etc.).

**Comment by jamesmartin** [comment]
Fixed the problem with existing classes being replaced in [v0.11.0](https://github.com/jamesmartin/inline_svg/blob/990dd45c544d05d10cdf39301dfb2696a3c3f5e7/CHANGELOG.md#0110---2016-07-24).

Closing this now in favor of #47.
