### ISSUE TITLE
Duplicate 'desc' elements when one is already in svg

### ISSUE THREAD

**Issue by gideonheilbron** [jamesmartin/inline_svg#46]
Just like 'title' in issue #31 does 'desc' add another element when the svg already has a desc. defined.

**Comment by jamesmartin** [comment]
@gideonheilbron yep, looks like the same problem. Time to extract some de-duping behavior I think…

**Comment by jamesmartin** [comment]
Fixed in [v0.11.0](https://github.com/jamesmartin/inline_svg/blob/990dd45c544d05d10cdf39301dfb2696a3c3f5e7/CHANGELOG.md#0110---2016-07-24).

**Comment by gideonheilbron** [comment]
Awesome @jamesmartin ! Thank you ❤️
