### ISSUE TITLE
Support for complicated data attributes

### ISSUE THREAD

**Issue by ollie** [jamesmartin/inline_svg#50]
Hello,

would it be possible to add support for complicated data attributes to behave more like `content_tag` does? Currently it seralizes the hash into a string, which is not very useful. :)

Example usage:
```ruby
inline_svg('iconmonstr-glasses-12-icon.svg', data: { tooltip: { id: 'id', placement: 'right' } })
```

Let me know if I need to provide more info, happy to help.

**Comment by ollie** [comment]
Whoops, my bad, somehow I thought this was the default behaviour (too much stress today?).

**Comment by ollie** [comment]
It seems the default behavior is to dasherize the keys so I guess it still is a form of bug:

```erb
Default:
<%= link_to 'a', '#', data: { tooltip_id: 'id', tooltip_placement: 'right' } %>
<a data-tooltip-id="id" data-tooltip-placement="right" href="#">a</a>

InlineSvg:
<%= inline_svg 'caret-up.svg', data: { tooltip_id: 'id', tooltip_placement: 'right' } %>
<svg xmlns="http://www.w3.org/2000/svg" width="34" height="34" viewBox="0 0 34 34" data-tooltip_id="id" data-tooltip_placement="right">
  <path d="M17 4.541l16.04 23.919h-32.08z"></path>
</svg>
```

Do you want another issue for this or should I reopen this one?

**Comment by jamesmartin** [comment]
@ollie sorry I missed this at the time, I guess it's because you closed the issue.

I've opened a new issue for the dasherize problem: #51.
