### ISSUE TITLE
Can you pass links to your inline_svg helper method?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [jamesmartin/inline_svg#68]
I'm currently trying to build buttons using a little bit of css and your helper method. Is it possible to pass link_to or turn your svg helper method into a button?

**Comment by jamesmartin** [comment]
@RailsCod3rFuture you could try using the block form of `link_to`, like this:

```erb
<%= link_to "/some/path" do %>
  <%= inline_svg "some-svg" %>
<% end %>
```

**Comment by jamesmartin** [comment]
@RailsCod3rFuture I'm going to close this issue now. Feel free to ping me if you have further questions.
