### ISSUE TITLE
Support absolute file paths

### ISSUE THREAD

**Issue by elstgav** [jamesmartin/inline_svg#70]
I’m loading our SVG icon set outside of the assets folder, to avoid the asset pipeline and costly asset compilation. But `inline_svg` doesn’t recognize absolute file paths, since it relies on sprockets’ `.find_asset` method.

Here’s what I’d like: `= inline_svg '/absolute/path/to/file.svg'` (currently not found through sprockets)

Here’s how I had to reconfigure `AssetFile`:

```rb
## config/initializers/inline_svg.rb

class InlineSvgAbsoluteAssetFile < InlineSvg::AssetFile
  def self.named(filename)
    path = Pathname.new(filename)

    path.absolute? && path.file? ? File.read(path) : super(filename)
  end
end


InlineSvg.configure do |config|
  config.asset_file = InlineSvgAbsoluteAssetFile
end
```

Can you add support for absolute file paths? I’m assuming it would require a few lines added to either `AssetFile` or `FindsAssetPaths`

**Comment by jamesmartin** [comment]
@elstgav thanks for the feedback, I appreciate you taking the time to write up this issue.

> I’m loading our SVG icon set outside of the assets folder, to avoid the asset pipeline and costly asset compilation. But inline_svg doesn’t recognize absolute file paths, since it relies on sprockets’ .find_asset method.

Have you considered using the [boot-time asset caching](https://github.com/jamesmartin/inline_svg#caching-all-assets-at-boot-time) configuration? This accepts any absolute paths you choose and pre-loads all SVG documents during the Rails boot process. The configuration would look something like this:

```ruby
InlineSvg.configure do |config|
  config.asset_file = InlineSvg::CachedAssetFile.new(
    paths: [
      "/absolute/path/to",
      "/some/other/absolute/path/of/your/choosing"
    ],
    filters: /\.svg/
  )
end
```

Then you could either call `inline_svg` and pass the absolute path, or you could pass just a fragment:

```ruby
<%= inline_svg "/absolute/path/to/file.svg" %>
<%= inline_svg "/absolute/path/to/file" %>
<%= inline_svg "file.svg" %>
<%= inline_svg "of/your/choosing/other-file" %>
```

> Can you add support for absolute file paths? I’m assuming it would require a few lines added to either AssetFile or FindsAssetPaths

I'll definitely keep this in mind for a future update. Alternatively, if you have the motivation and wanted to try adding this behavior yourself, I'd be happy to work with you on a pull request.

**Comment by elstgav** [comment]
The problem is we’re using an icon library with thousands of SVGs; we’re only using a few of them so far, so I’m assuming boot-time caching the entire library would be overkill.

If more people are interested in absolute file paths I can open a PR, otherwise the patch I’m using works well enough for me now. Thanks for the plugin!

**Comment by jamesmartin** [comment]
> The problem is we’re using an icon library with thousands of SVGs; we’re only using a few of them so far, so I’m assuming boot-time caching the entire library would be overkill.

It would be interesting to see what kind of penalty in terms of memory overhead and boot time increase you would pay for adding the entire icon library path and caching them on boot. But I understand your hesitation in this case.


> If more people are interested in absolute file paths I can open a PR, otherwise the patch I’m using works well enough for me now.

Thanks for offering to do that, I appreciate your feedback and any help you can spare with adding features in future.

I'm going to close this issue now, but will refer people to this thread if they have the same problem.
