### ISSUE TITLE
Feature request: `aria-hidden`

### ISSUE THREAD

**Issue by tysongach** [jamesmartin/inline_svg#72]
👋 

Huge high-fives all-around for the accessibility features this gem already offers. It’s so handy to be able to pass in titles and descriptions when you call on an SVG. I’d like to discuss furthering the accessibility features by allowing the hiding of SVGs using `aria-hidden`.

Sometimes SVGs are simply decorative and therefore should be removed from the accessibility tree. Here’s an example: 

```erb
<p>
  <%= inline_svg "checkmark-icon.svg" %>
  Success!
</p>
```

You can imagine this as a simple flash message, letting the user know that their action succeeded. We have the word ‘Success’, preceded by a checkmark icon to visually represent the state. 

In such a situation, the icon is simply decorative; it’s repeating content already conveyed by the word ‘Success.’ If we apply `aria-hidden="true"` to the SVG, we can remove it from the accessibility tree and avoid the repetition.

## Possible solution?

I’ve not dug into the specifics of how the `aria` option works, but perhaps passing it a `hidden` value could work (edit: [see comment below](https://github.com/jamesmartin/inline_svg/issues/72#issuecomment-334582026)):

```erb
<%= inline_svg "icon.svg", aria: "hidden" %>
```

```xml
<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg">
  …
</svg>
```

**Comment by tysongach** [comment]
Perhaps this is a good issue for a [`Hacktoberfest` label](https://hacktoberfest.digitalocean.com/)?

**Comment by jamesmartin** [comment]
@tysongach thanks for taking the time to write up this suggestion. I'm generally 👍 on any feature that improves things from an accessibility perspective.

As for the interface, my preference would be to make this an explicit option, requiring a value. E.g.

```ruby
<%= inline_svg "icon.svg", aria_hidden: true %>
```

**Comment by seanpdoyle** [comment]
@jamesmartin @tysongach is this already supported?

https://github.com/jamesmartin/inline_svg/blob/25fa64e0b5143c2caa98b837b65697744cd4b5c7/spec/helpers/inline_svg_spec.rb#L132-L141

Could something like this work?

```erb
<%= inline_svg "icon.svg", "aria-hidden" => true %>
```

**Comment by jamesmartin** [comment]
> is this already supported?

@seanpdoyle it's possible to implement via custom transformations, but each user of the gem would have to implement their own version. Is that what you had in mind?

**Comment by seanpdoyle** [comment]
@jamesmartin for custom attribute support, are there additional steps to take other than `"aria-hidden" => true`?

```erb
<%= inline_svg "icon.svg", "aria-hidden" => true %>
```

**Comment by tysongach** [comment]
I should’ve been more clear in my original description, but yes, this is possible today via custom transformations:

```rb
class AriaHiddenAttribute < InlineSvg::CustomTransformation
  def transform(doc)
    doc = Nokogiri::XML::Document.parse(doc.to_html)
    svg = doc.at_css "svg"
    svg["aria-hidden"] = value
    doc
  end
end


InlineSvg.configure do |config|
  config.add_custom_transformation(
    attribute: :aria_hidden,
    transform: AriaHiddenAttribute,
  )
end
```

**Comment by jamesmartin** [comment]
> for custom attribute support, are there additional steps to take other than "aria-hidden" => true?

@seanpdoyle yes, see @tysongach's [example code](https://github.com/jamesmartin/inline_svg/issues/72#issuecomment-335206874).

**Comment by seanpdoyle** [comment]
@tysongach @jamesmartin https://github.com/jamesmartin/inline_svg/pull/79

**Comment by jamesmartin** [comment]
@seanpdoyle thanks for opening the PR for this. Great minds think alike, I think we both just implemented the same thing. See #78 😁

I'll merge yours so you get the contribution credit.
