### ISSUE TITLE
Fallback SVG

### ISSUE THREAD

**Issue by meowsus** [jamesmartin/inline_svg#73]
Hey @jamesmartin. 

This use case is a bit weird, but I wanted to get your take on it. I couldn't think of a way to solve it using a transformation, but I might have been missing something obvious.

In our platform, developers can use a custom DSL to create a specific type of object in the system called a Content Block. Each Content Block is graphically represented within the administration area of the site. A developer can upload an SVG so that the Content Block they created renders not only the name, but also a real nice icon as well.

The problem is that the icon isn't required, in a technical sense, which actually was the catalyst for the opening of [that default CSS class PR i did](https://github.com/jamesmartin/inline_svg/pull/67).

Taking this one step further, I'm curious if you find it useful to offer a fallback SVG path as part of the API?

```rb
inline_svg('path/to/my/risky.svg, fallback: 'totally/safe/fallback.svg')
```

**Comment by jamesmartin** [comment]
@meowsus I'm not opposed to this idea. We would need to reserve the `:fallback` param in perpetuity, meaning no custom transformations named `Fallback` could be used, which doesn't seem like a huge problem but would be a breaking change.

I'd be happy to help you get a PR merged if you're keen to work on this feature.

**Comment by meowsus** [comment]
Closing, since the spike in #74 was merged.
