### ISSUE TITLE
Aria SVGs with identical titles create IDs with identical values

### ISSUE THREAD

**Issue by sonniesedge** [jamesmartin/inline_svg#76]
Thank you so much for this gem! It's really helped us get accessible SVGs up and running on our project. 👍 🎷  

I've noticed that if you create two ARIA-eqipped SVGs with the same value for "title", an ID of the same value is created inside both. Given that a site may have several versions of an SVG on a page -
 each performing the same action, such as "close" - this presents a problem, as IDs would be duplicated within a page. 

```
      <%= inline_svg 'detail_lite/popup_close.svg', title: "Close", aria: true %>
           ...
           [later in document]
           ...
      <%= inline_svg 'detail_lite/popup_close.svg', title: "Close", aria: true %>
```

Output:

```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" role="img" aria-labelledby="anc36311bbwgjzxa2nhpdtms5sa19q0">
<title id="anc36311bbwgjzxa2nhpdtms5sa19q0">Close</title>
<path d="M.032 3.531L3.527.035l12.441 12.434-3.494 3.496z"></path><path d="M12.473.037l3.494 3.495L3.529 15.966.035 12.471z"></path></svg>

...

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" role="img" aria-labelledby="anc36311bbwgjzxa2nhpdtms5sa19q0">
<title id="anc36311bbwgjzxa2nhpdtms5sa19q0">Close</title>
<path d="M.032 3.531L3.527.035l12.441 12.434-3.494 3.496z"></path><path d="M12.473.037l3.494 3.495L3.529 15.966.035 12.471z"></path></svg>
```

I understand that I could add a value to the `desc` parameter, but this is less than ideal, as it introduces unnecessary verbosity, for no added value for the user. 

I could also give a different `title` value to all similar SVGs. But this would require creating a different value for each one, creating extra work, and inconsistency. 

Thank you again!

**Comment by jamesmartin** [comment]
@sonniesedge thanks for opening this issue and the detailed description of the problem. This definitely could use some work.

I think it should be fairly easy to introduce a random factor into the [`InlineSvg::IdGenerator.generate`](https://github.com/jamesmartin/inline_svg/blob/51fbae79199c27eb876a9f0d3f8556cf67d58015/lib/inline_svg/id_generator.rb#L4) to prevent ID collisions in future. I'll get on that.

**Comment by jamesmartin** [comment]
Added some randomness to the ID generation in #77.

**Comment by sonniesedge** [comment]
Great to hear! Thank you for the prompt response. 😀 🎉

**Comment by tysongach** [comment]
Woohoo! Been experiencing this, as well. Super happy to see an improvement coming.
