### ISSUE TITLE
Missing array in cached_asset_file.rb

### ISSUE THREAD

**Issue by DustinArmstrong** [jamesmartin/inline_svg#81]
Added an array where one appears to be missing.
Causes this error in Rails 4.0.3:
```
/gems/inline_svg-1.3.0/lib/inline_svg/cached_asset_file.rb:17: syntax error, unexpected ',' (SyntaxError)
    def initialize(paths:, filters: [])
```

Fix suggested in https://github.com/jamesmartin/inline_svg/pull/80

**Comment by jamesmartin** [comment]
Only visible in Ruby versions older than 2.1, which introduced required keyword arguments. The fix from #80 has been merged. Thanks again, @DustinArmstrong! ✨

**Comment by DustinArmstrong** [comment]
@jamesmartin Would this be a candidate for a `1.3.1` release of the gem?

**Comment by jamesmartin** [comment]
> Would this be a candidate for a 1.3.1 release of the gem?

@DustinArmstrong yes, if it's helpful I can make a new release today.

**Comment by jamesmartin** [comment]
[v1.3.1](https://github.com/jamesmartin/inline_svg/releases/tag/v1.3.1) was released today.
