### ISSUE TITLE
Accessibility: invalid digests for id aria-labelled-by

### ISSUE THREAD

**Issue by endorfin** [jamesmartin/inline_svg#87]
Sometimes the hash is generated with a number at the beginning. That is not a valid XML name.

> Error: Bad value **91eoerhog4s3pt89llvssg0cmfrpoam** for attribute **id** on element **title**: Not a valid XML 1.0 name.

**Comment by jamesmartin** [comment]
Fixed by @endorfin in #88. This will ship in the next minor version bump.
