### ISSUE TITLE
`inline_svg` does not use sprockets manifest

### ISSUE THREAD

**Issue by wjdhamilton** [jamesmartin/inline_svg#89]
As the title suggests, I can't get `inline_svg` to get its filenames from the sprockets manifest. 

I am using CloudFront as my CDN, and have deployed my app on Heroku. All the assets are precompiled before deployment using `rake assets:precompile`. I am using the `.svg` suffix as recommended. 

How do I get `inline_svg` to use the sprockets manifest?

I'm using Rails 5.2.0 and inline_svg-1.3.1

Thanks for your help!

**Comment by wjdhamilton** [comment]
Taking your advice and adding the caching initialiser suggested in the README has fixed this. Thank you the suggestion and the gem!

**Comment by jamesmartin** [comment]
@wjdhamilton sorry you had trouble using the sprockets manifest. I am going to look into that issue separately. Glad you were able to use the boot time caching to get things working in the meantime. 👌

**Comment by P9GIT** [comment]
Same problem here.
Sprockets is not used and I just get the plain asset name without the appended hash.

**Comment by P9GIT** [comment]
@jamesmartin 
Upon my first reporting of this issue I did a more thorough investigation to find the exact conditions.
I found out that someone sloppily added SVG calls NOT using the inline-svg gem.
So this is a breach of policy in our code and not a bug in the inline-svg gem.
I'm sorry to have wasted your time.

**Comment by jamesmartin** [comment]
@P9GIT thanks for following up to confirm the root cause of the problem you were experiencing. I appreciate you taking the time! 👍 ✨
