### ISSUE TITLE
Feature request: Raise error if missing SVG Files

### ISSUE THREAD

**Issue by elalemanyo** [jamesmartin/inline_svg#93]
Hi,
I would like to raise error if sag is missing, is it possible to do this?
I think it would be something interesting.

Thanks

**Comment by jamesmartin** [comment]
@elalemanyo thanks for the suggestion. I have implemented this feature on a branch in https://github.com/jamesmartin/inline_svg/pull/94, if you're interested to take a look.

**Comment by jamesmartin** [comment]
Released in [v1.4.0](https://github.com/jamesmartin/inline_svg/releases/tag/v1.4.0).
