### ISSUE TITLE
Not working without sprockets

### ISSUE THREAD

**Issue by askehansen** [jamesmartin/inline_svg#95]
When using this in a new rails 6 app i get the error:
`undefined method 'assets' for #<Rails::Application::Configuration:0x00007ffba1c234f0>`

I guess it fails here because rails 6 now uses webpacker instead of sprockets:
https://github.com/jamesmartin/inline_svg/blob/8e9c3afff89838cc42f35ff97979d9747581e50e/lib/inline_svg/static_asset_finder.rb#L16

**Comment by jamesmartin** [comment]
@askehansen thanks for opening this issue. 👍 

> I guess it fails here because rails 6 now uses webpacker instead of sprockets:

That seems the most likely cause of the problem. I haven't had a chance to try this gem with a vanilla Rails 6 project yet. I'll put this on my todo list.

**Comment by jamesmartin** [comment]
Just tested with by [upgrading a Rails 5.2 app to Rails 6.0.0.rc1](https://github.com/jamesmartin/inline_svg_test_app/tree/rails6): `inline_svg` still works with Rails 6 _if_ you use Sprockets.

I'll have to figure out what's needed to make it work with Webpacker.

**Comment by askehansen** [comment]
Okay so I just noticed I had `--skip-sprockets` in my `~/.railsrc` file.
That means this issue is not regarding rails 6, but an issue if you disable sprockets in favor of using webpacker. Sorry for the confusion!

However I would like to contribute in making this gem not relying on sprockets.

What is the disadvantage of doing this instead?
```ruby
class StaticAssetFinder
...

  def pathname
    Rails.root.join('assets', @filename)
  end
end
```

**Comment by askehansen** [comment]
I realized I can write my own asset file loader and just use that instead:
```ruby
class BasicAssetFileLoader
  def self.named(filename)
    File.open("app/assets/#{filename}", "rb") do |file|
      file.read
    end
  end
end

InlineSvg.configure do |config|
  config.asset_file = BasicAssetFileLoader
end
```

Again, sorry for the confusion and not reading the documentation!
And thanks for a great gem! 😊👍

**Comment by jamesmartin** [comment]
Added support for Webpacker in [v1.5.0](https://github.com/jamesmartin/inline_svg/releases/tag/v1.5.0)
